name: Build and Run C Program

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build with Makefile
        run: make all

      - name: Make runall.sh executable
        run: chmod +x ./runall.sh

      - name: Run the program
        run: ./runall.sh
